spring:
  h2:
    console:
      enabled: true
  jpa: # jpa 프로퍼티스 빈에 주입이 됨
    generate-ddl: true
    #hiberate:
      #ddl-auto: create-drop
    database: H2
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        querry.in_clause_parameter_padding: true
        hbm2ddl:
          auto: create-drop
